### PR TITLE
Try requiring Ember if possible instead of using it as a global

### LINKED ISSUE #70: Deprecation warnings with Ember 3.27
All [these](https://github.com/emberjs/ember-classic-decorator/blob/v2.0.0/vendor/classic-decorator/index.js#L13) usages cause Ember 3.27 to trigger deprecation warnings. It would be nice to have those fixed before Ember 4 as otherwise `ember-classic-decorator` won't be usable with it.

Somewhat related to #63.

### PR DESCRIPTION
**Pull request by boris-petrov**
Fixes #70 

cc @rwjblue

I've copied what you gave in #70 as example code but I added `.default` after the `require` - I believe it's necessary?

### CODE REVIEW

**Comment by boris-petrov** [comment]
@rwjblue ping. :)

**Comment by charlesfries** [comment]
Anything I can do to help get a #70 fix merged?

**Comment by boris-petrov** [comment]
@rwjblue ping. :)

**Comment by gzurbach** [comment]
I would love to see this merged as well. This might be the last issue preventing me from upgrading to Ember 4. I was able to clear all deprecations warnings in my app on Ember 3.28, besides this one:

> Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.

The call stack indicates the warning comes from this library, which I can't remove quite yet due to other issues.

**Pull request closed without merging**
